### ISSUE TITLE
Current version is not compatible with MantisBT 2.x

### ISSUE THREAD

**Issue by wuxipaopao** [mantisbt-plugins/GanttChart#10]
Current version is not compatible with MantisBT 2.x, can you fix it?

**Comment by P4z** [comment]
I would love to see this being available for Mantis Release 2.5.1

**Comment by dregad** [comment]
I don't maintain this plugin so I can't really speak for its author @AlainD-, but considering the fact that it relies on _jpgraph_ library and support for that has been removed in Mantis 2.x, I believe that adapting the code is not going to be a simple task, likely involving a rewrite using a different graph library (e.g. [jQuery.Gantt](http://mbielanczuk.com/jquery-gantt/) or similar).

**Comment by spmeesseman** [comment]
doesn't seem like anyone is really looking for this plugin anymore but i did patch it up to get it semi-working.  just need to adjust code for ace theme but ill have that done soon as my co wants this functionality.  I have all my plugins I'm working on at https://github.com/spmeesseman/mantisbt-plugins.
@dregad i saw you mentioned moving them to the mantisbt-plugins account on one of the mantisbt tickets, when they are all complete and I find the time I'll try to do that.  For now this is much easier for me as I've done about 6 of them and a few more to go

**Comment by dregad** [comment]
@AlainD- As mentioned above @spmeesseman has updated the plugin and kindly offered to take over its maintenance (see also discussion in https://mantisbt.org/bugs/view.php?id=25946) . 

Unless you object to this, I will grant him push access to the repository.

**Comment by AlainD-** [comment]
Ho yes, please grant access :-) I wanted the plugin officially in the mantisbt plugins repo so that I won't need to update it myself, because I do not develop any more.

**Comment by dregad** [comment]
Thanks for the feedback @AlainD- 

@spmeesseman Congratulations, you are now the official maintainer for this plugin :grin:

**Comment by spmeesseman** [comment]
working in v2.21.1 now
