### ISSUE TITLE
Characters problem

### ISSUE THREAD

**Issue by moderatoo** [mantisbt-plugins/GanttChart#3]
![gantt](https://cloud.githubusercontent.com/assets/10581644/5791826/b1a8c016-9ef4-11e4-9b4c-2d99b782079b.png)
Hi 
I have problem with polish charsets. Gantt Char don't display any polish chars.
I use fonts with polish chars (arial.ttf) but this doesn't help.
What is the solution? I use text with UTF-8 without BOM

**Comment by friedrico** [comment]
Same problem with German Umlauts here :(

**Comment by friedrico** [comment]
https://github.com/mantisbt-plugins/GanttChart/compare/master...friedrico:patch-1
That patch fixes this for me

**Comment by AlainD-** [comment]
Fixed with 1a1cadb3ebc90a7a8233eace78632490b37554e6
