### ISSUE TITLE
MantisBT 1.3 Beta

### ISSUE THREAD

**Issue by Dimas-sc** [mantisbt-plugins/GanttChart#4]
Do you have plans to make it work with Mantis 1.3? Now it have the dependence of the "MantisBT Core 1.2.0" and it can't be installed in the 1.3 version.

**Comment by AlainD-** [comment]
MantisBT 1.3 is not released yet, and I personally have no idea of the differences with the version 1.2.x. But I suppose that if you change the dependencies in your installed copy of the plugin, it would probably fix it?

**Comment by Dimas-sc** [comment]
Changing the dependence to MantisBT Core 1.3 I can install it, but when I try to access to the chart I only see an ugly error saying that .../GanttChart/core/graph_api.php is missing. I copied this file from another plugin but another error appears: .../GanttChart/core/version-api.php is missing.

I know 1.3 is in beta yet, but I wanted to try if you knew how to fix it. No problem, I'll wait, thx.

**Comment by dregad** [comment]
I'm not sure how the how the plugin is managing the dependencies with MantisBT core, but FYI there are several known issues with the graph (plugin) API in MantisBT 1.3 which may (or may not) cause this kind of behavior. I'm planning to fix these before 1.3 goes live.

What might also cause this error, is the switch in 1.3 from use of PHP's require_once() function, to custom functions require_api() and require_lib().

**Comment by AlainD-** [comment]
Damien,
How do now require a plugin function? If I want to require graph_api.php
for instance? None of the require_once, require_api and require_lib
actually work.

Is the only option to declare a variable with the plugin path
($t_graph_path = 'something';) and use it in a require_once($t_graph_path .
'graph_api.php') or is there an existing api for that purpose ?

Thanks.

On Wed, Jan 21, 2015 at 10:07 AM, Damien Regad <notifications@github.com>
wrote:

> I'm not sure how the how the plugin is managing the dependencies with
> MantisBT core, but FYI there are several known issues with the graph
> (plugin) API in MantisBT 1.3 which may (or may not) cause this kind of
> behavior. I'm planning to fix these before 1.3 goes live.
>
> What might also cause this error, is the switch in 1.3 from use of PHP's
> require_once() function, to custom functions require_api() and
> require_lib().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mantisbt-plugins/GanttChart/issues/4#issuecomment-70805135>
> .
>



-- 

AlainD.

**Comment by atrol** [comment]
Didn't have a deeper look.
Might help some way https://github.com/mantisbt-plugins/EmailReporting/commit/d0de5529a7fff966a82531111f06da4d03aaee17

**Comment by AlainD-** [comment]
OK, no I found it. Actually I have to use:
plugin_require_api( 'core/graph_api.php', 'MantisGraph' );

but strangely I need to prefix the attribute file with 'core/' for this
method, while the main require_api already knows to search inside the main
core folder.
Anyway, it fixed the reference issue I had. Thank you for you help.

AlainD.

On Wed, Jan 21, 2015 at 11:38 AM, Roland Becker <notifications@github.com>
wrote:

> Didn't have a deeper look.
> Might help some way mantisbt-plugins/EmailReporting@d0de552
> <https://github.com/mantisbt-plugins/EmailReporting/commit/d0de5529a7fff966a82531111f06da4d03aaee17>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mantisbt-plugins/GanttChart/issues/4#issuecomment-70816406>
> .
>



-- 

AlainD.

**Comment by dregad** [comment]
The original purpose of `plugin_require_api()`, which was actually written long before `require_api()`, is to include a *plugin-specific* file; the function is not aware of "standard" location for files (i.e. *core/* in this case), for the simple reason that we never defined such a standard... Consequently, it is normal in this context that you had to specify `'core/graph_api.php', 'MantisGraph'`.

**Comment by AlainD-** [comment]
Just fixed. You can download the last master src to use it with mantisBT v1.3

**Comment by Dimas-sc** [comment]
Thx!
