### ISSUE TITLE
It'd be nice same version of the plugin compatible with both 1.2.x&1.3.x Mantisbt Branches

### ISSUE THREAD

**Issue by edupulpillo** [mantisbt-plugins/GanttChart#7]
It'd be nice same version of the source code of the plugin compatible with both 1.2.x&1.3.x Mantisbt Branches. Thanks for the plugin, very useful.

**Comment by dregad** [comment]
Considering that 1.2 is no longer maintained, and 1.3 is only receiving security patches, this issue does not make sense anymore.
